set(LIB_NAME PhysX)

find_path(
	PHYSX_INCLUDE_DIR PxPhysicsAPI.h
)

find_path(
	PHYSX_SHARED_INCLUDE_DIR foundation/Px.h
)

find_library(
	PHYSX_LIB PhysX_64
)

find_library(
	PHYSX_LIB_COMMON PhysXCommon_64
)

find_library(
	PHYSX_LIB_FOUNDATION PhysXFoundation_64
)

find_library(
	PHYSX_LIB_EXTENSIONS PhysXExtensions_static_64
)

set(LIBS ${PHYSX_LIB} ${PHYSX_LIB_COMMON} ${PHYSX_LIB_FOUNDATION} ${PHYSX_LIB_EXTENSIONS})
message(STATUS "---------------------------- ${LIBS}")


include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	PhysX
	REQUIRED_VARS
		PHYSX_INCLUDE_DIR
		PHYSX_SHARED_INCLUDE_DIR
		PHYSX_LIB
		PHYSX_LIB_COMMON
		PHYSX_LIB_FOUNDATION
		PHYSX_LIB_EXTENSIONS
)

add_library(PhysX STATIC IMPORTED)

set_target_properties(PhysX PROPERTIES
	IMPORTED_LOCATION ${LIBS}
	IMPORTED_IMPLIB ${LIBS}
	INTERFACE_INCLUDE_DIRECTORIES "${PHYSX_INCLUDE_DIR};${PHYSX_SHARED_INCLUDE_DIR}"
)

add_library(PhysXCommon STATIC IMPORTED)
set_target_properties(PhysXCommon PROPERTIES
	IMPORTED_LOCATION ${PHYSX_LIB_COMMON}
	IMPORTED_IMPLIB ${PHYSX_LIB_COMMON}
	INTERFACE_INCLUDE_DIRECTORIES "${PHYSX_INCLUDE_DIR};${PHYSX_SHARED_INCLUDE_DIR}"
)

add_library(PhysXFoundation STATIC IMPORTED)
set_target_properties(PhysXFoundation PROPERTIES
	IMPORTED_LOCATION ${PHYSX_LIB_FOUNDATION}
	IMPORTED_IMPLIB ${PHYSX_LIB_FOUNDATION}
	INTERFACE_INCLUDE_DIRECTORIES "${PHYSX_INCLUDE_DIR};${PHYSX_SHARED_INCLUDE_DIR}"
)

add_library(PhysXExtensions STATIC IMPORTED)
set_target_properties(PhysXExtensions PROPERTIES
	IMPORTED_LOCATION ${PHYSX_LIB_EXTENSIONS}
	IMPORTED_IMPLIB ${PHYSX_LIB_EXTENSIONS}
	INTERFACE_INCLUDE_DIRECTORIES "${PHYSX_INCLUDE_DIR};${PHYSX_SHARED_INCLUDE_DIR}"
)

target_link_libraries(PhysX INTERFACE
	PhysXCommon
	PhysXFoundation
	PhysXExtensions
)
